apiVersion: v1
kind: Service
metadata:
  name: nephio-webui
  namespace: nephio-webui
spec:
  type: ClusterIP
  selector:
    app: nephio-webui
  ports:
    - name: http
      port: 7007
      targetPort: http
